version: 2.1
orbs:
  node: circleci/node@5.2
jobs:
  test-v20:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "20.19"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
          environment:
            NODE_ENV: test
            CI: true
            TEST_ENV: true
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run Prettier
          command: npm run format:check
      - run:
          name: Verify build
          command: echo "Build and tests completed successfully!"
  
  test-v22:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: "22.17"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
          environment:
            NODE_ENV: test
            CI: true
            TEST_ENV: true
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run Prettier
          command: npm run format:check
      - run:
          name: Verify build
          command: echo "Build and tests completed successfully!"
  
  test-v24:
    docker:
      - image: cimg/node:24.3
    steps:
      - checkout
      - node/install:
          node-version: "24.3"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
          environment:
            NODE_ENV: test
            CI: true
            TEST_ENV: true
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run Prettier
          command: npm run format:check
      - run:
          name: Verify build
          command: echo "Build and tests completed successfully!"

workflows:
  build_and_test:
    jobs:
      - test-v20
      - test-v22
      - test-v24