name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & run tests
        run: |
          npm ci
          npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: site

      # Prepare a combined deploy directory (_deploy) to include site + coverage
      - name: Prepare deploy directory
        run: |
          rm -rf _deploy
          mkdir -p _deploy
          cp -r site/* _deploy/
          mkdir -p _deploy/coverage
          cp -r coverage/lcov-report/* _deploy/coverage/
          # Move legal pages to /terms and /privacy
          mkdir -p _deploy/terms
          cp _deploy/terms-of-service.html _deploy/terms/index.html
          rm _deploy/terms-of-service.html
          mkdir -p _deploy/privacy
          cp _deploy/privacy-policy.html _deploy/privacy/index.html
          rm _deploy/privacy-policy.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _deploy

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Cleanup
        run: |
          rm -rf node_modules
          rm -rf coverage
          rm -rf site
          echo "Cleanup completed successfully!"
      - name: Finalize
        run: echo "Deployment to GitHub Pages completed successfully!"
      - name: Notify success
        run: echo "Deployment to GitHub Pages completed successfully!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}